k_max: 20
min_coverage: 2
sp_time_limit: 60
sc_time_limit: 30
n_segments: 50
decay: 0.95
solver_workers: 4
instance_workers: 7
selectors:
  type: ucb
  exploration: 1.41
solvers:
  - hgs
  - filo
  - filo2
  - ails2
vertex_methods:
  - kmeans
  - dbscan
  - kmedoids
  - spectral
  - angular
route_methods:
  - hierarchical
  - kmeans
  - overlap_graph
  - demand_aware
